# Spring Properties

spring.application.name=KeeperAppServer
server.port=8090

info.app.name=Spring Boot Rest API for Keeper App Server
info.app.description=Configuration of Spring for IntelliJ
info.app.version=1.0.0

# Database Properties

spring.datasource.url=jdbc:mysql://localhost:3306/keeperapp_db
spring.datasource.username=root
spring.datasource.password=Niladri#1000

#JPA Hibernate Properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.generate-ddl=true
